require("hya.options")
require("hya.keymaps")
require("hya.plugins")
require("hya.colorscheme")
require("hya.options")
require("hya.cmp")
require("hya.lsp")
require("hya.telescope")
require("hya.treesitter")
require("hya.autopairs")
require("hya.comment")
require("hya.gitsigns")
require("hya.nvim-tree")
require("hya.bufferline")
require("hya.toggleterm")

-- Load the colorscheme
require("nord").set()
